name: Streamlit Dashboard CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Auto-format code with Black
      run: |
        pip install black
        black .

    - name: Run tests with pytest
      run: |
        pip install pytest
        pytest tests/

    - name: Check for syntax errors
      run: |
        python -m compileall .

    - name: Run basic test (Streamlit dry run)
      run: |
        streamlit run app.py --server.headless true --server.runOnSave false &
        sleep 10
        pkill streamlit
